=== lupidux/localCommunity/code/xml/steps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="steps">
        <xsd:complexType> 
            <xsd:sequence>
                <xsd:element ref="step" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="step">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idProgetto" />
                <xsd:element ref="testo" />
                <xsd:element ref="immagine" />
            </xsd:sequence>

            <xsd:attribute name="id" type="xsd:integer" use="id" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idProgetto" type="xsd:integer" />
    <xsd:element name="testo" type="xsd:string" />
    <xsd:element name="immagine" type="xsd:string" />

</xsd:schema>

=== lupidux/localCommunity/code/xml/steps_img_omesse.xml
<?xml version="1.0" encoding="UTF-8"?>
<steps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="steps.xsd">
    <step id="1">
        <idProgetto>1</idProgetto>
        <testo>           
            What’s inside?

            We learned a lot from working on the original PinePhone. Over the past two years we painstakingly collected and analyzed your feedback and explored all avenues for hardware improvements. The PinePhone Pro is the end result of this journey. It is powered by a Rockchip hexa-core SoC operating at 1.5GHz, and ships paired with 4GB of dual-channel LPDDR4 RAM as well as 128GB of internal eMMC flash storage. It features a high-fidelity 13MP main camera sensor and a 5MP front-facing camera.

            We worked closely with Rockchip’s engineering team to fine-tune the SoC’s performance so that it meets the necessary thermal and battery-consumption envelopes. The result of this cooperation is the RK3399S – a RK3399 variant made specifically for the PinePhone Pro. Rockchip’s team was also instrumental in enabling the PinePhone Pro’s suspend state, which allows the smartphone to receive calls and SMS messages while preserving battery.

            Hardware privacy dip switches for the cameras, the microphone, WiFi and BT, headphone jack (enabling UART) and the LTE modem (including GPS) are accessible under the back cover, just as on the original PinePhone.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="2">
        <idProgetto>1</idProgetto>
        <testo>
            What’s the outside like?

            We wanted the PinePhone Pro to reflect its status as a pro-grade device while maintaining perfect compatibility with all existing PinePhone peripherals. The PinePhone Pro uses the same pogo-pin systems and back cover attachment as the original PinePhone, making it compatible with all existing add-ons. The keyboard, PineDio LoRa, fingerprint reader and wireless charging cases will all work with the PinePhone Pro. 

            The PinePhone Pro features a vibrant in-cell IPS display covered with Corning Gorilla Glass 4™  with an oleophobic coating, offering superior scratch resistance and image clarity. The camera is covered by Corning Gorilla Glass 4™ and protected by an elevated bezel, similar to the one found on the original PinePhone.

            The chassis is slightly thicker (~2mm) than the original PinePhone’s. Proportions of the original design were altered to accommodate the new display and to allow for improved heat dissipation. The coating on the back of the PinePhone Pro has been given a premium feel and engineered to minimize oily fingerprints. We think you’ll be pleased with the end-result.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="3">
        <idProgetto>1</idProgetto>
        <testo>
            Who is it for?

            Contemporary mobile Linux operating systems have a way to go before they can be considered true alternatives to Android or iOS. While mobile Linux isn’t in a state that could satisfy most mainstream electronics consumers, we recognize that a sizable portion of our community is ready to make the jump to a Linux-only smartphone today. The PinePhone Pro has the raw horsepower to be your daily driver, granted you’re ready to accept the current software limitations. 

            In a nutshell: if you are an existing PinePhone owner and your only wish is for the device to be more powerful and refined, then the PinePhone Pro is for you.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="4">
        <idProgetto>1</idProgetto>
        <testo>     
            Who isn’t it for?

            We’re not in the business of selling empty promises – a much faster mainline Linux smartphone won’t make the existing operating systems more refined, nor will it magically spawn software replacements for your iOS or Android applications. There is a long road ahead of us, all of us, and it will require time and effort for the software to reach a degree of maturity that would satisfy mainstream users.

            If you depend on proprietary mainstream mobile messenger applications, banking applications, use loyalty or travel apps, consume DRM media, or play mobile video games on your fruit or Android smartphone, then the PinePhone Pro is likely not for you.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="5">
        <idProgetto>1</idProgetto>
        <testo>
            How’s the performance?

            Tasks such as opening applications, browsing the internet, interacting with the user interface or watching videos are on par with recent mid-range Android smartphones. Many of you will also be happy to hear that native Linux games as well as popular retro game emulators work great on the PinePhone Pro – be it SuperTuxKart, PSP, or Dreamcast emulation, you’ll be in for a treat. 

            When docked and connected to an external monitor and keyboard and mouse, the PinePhone Pro performs well when surfing the web, using the terminal or an office suite, watching 1080p videos, and even in light photo editing. The perfect pocketable Linux computer on the go.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="6">
        <idProgetto>1</idProgetto>
        <testo>
            What’s the availability like?

            We have started taking PinePhone Pro pre-orders from developers on October 15, 2021, and expect to have them delivered by December this year.

            We have also secured the necessary components and factory floor-time to produce a large production run of the PinePhone Pro in November; we’re calling it the Explorer Edition. If everything goes according to plan, early adopters will have their Explorer Edition units delivered in early 2022.

            Subscribe to our blog, Telegram and Discord news feeds or follow us on Twitter and Mastodon to be notified when Explorer Edition becomes available.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="7">
        <idProgetto>1</idProgetto>
        <testo>
            What does it run? 

            Openness means privacy and security as well as software choice. Just as the original PinePhone, the PinePhone Pro runs mainline Linux (with patches, which are being upstreamed) with open source drivers. 

            The default operating system for the PinePhone Pro is Manjaro Linux with KDE Plasma Mobile, but we expect to see it supported by most of the operating systems already available for the original PinePhone. It is also likely that PinePhone Pro will give rise to new software options. We cannot wait to see what the community comes up with.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="8">
        <idProgetto>1</idProgetto>
        <testo>
            How do I join the project?

            The PinePhone Pro boasts a large and vibrant community of developers, members of other mobile Linux projects and enthusiasts like yourself. We host an interconnected network of chats and forums which facilitate communication and cooperation. Everyone is welcome – join in!
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="9">
        <idProgetto>2</idProgetto>
        <testo>
            Mechanism

            Fusion reactions occur when two or more atomic nuclei come close enough for long enough that the nuclear force pulling them together exceeds the electrostatic force pushing them apart, fusing them into heavier nuclei. For nuclei heavier than iron-56, the reaction is endothermic, requiring an input of energy.[2] The heavy nuclei bigger than iron have many more protons resulting in a greater repulsive force. For nuclei lighter than iron-56, the reaction is exothermic, releasing energy when they fuse. Since hydrogen has a single proton in its nucleus, it requires the least effort to attain fusion, and yields the most net energy output. Also since it has one electron, hydrogen is the easiest fuel to fully ionize.

            The strong force acts only over short distances (at most one femtometre, the diameter of one proton or neutron), while the repulsive electrostatic force between nuclei acts over longer distances. In order to undergo fusion, the fuel atoms need to be given enough kinetic energy to approach each other closely enough for the strong force to overcome the electrostatic repulsion. The amount of kinetic energy needed to bring the fuel atoms close enough is known as the "Coulomb barrier". Ways of providing this energy include speeding up atoms in a particle accelerator, or heating them to high temperatures.

            Once an atom is heated above its ionization energy, its electrons are stripped away, leaving just the bare nucleus. This process is known as ionization, and the resulting nucleus is known as an ion. The result is a hot cloud of ions and free electrons formerly attached to them known as plasma. Because the charges are separated, plasmas are electrically conductive and magnetically controllable. Many fusion devices take advantage of this to confine the particles as they are heated.
        </testo>
        <immagine>
            <!-- img omessa -->
        </immagine>
    </step>
    <step id="10">
        <idProgetto>2</idProgetto>
        <testo>
            Cross section
